[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://whisk-81175bd1f0e4.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
